apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ns-event
spec:
  template:
    serviceAccountName: kube-argo
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.affinity }}
    affinity:
      {{- toYaml .Values.affinity | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  eventBusName: {{ .Values.eventBus | default "default" }}
  resource:
    ns-event:
      group: ""
      version: v1
      resource: namespaces
      eventTypes:
        - ADD
        - DELETE
      filter:
        afterStart: true