{{- if .Values.eventBus }}
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ .Values.eventBus | default "default" }}
spec:
  jetstream:
    auth: token
    version: "2.9.11"
    replicas: 3
    streamConfig: |
      maxAge: 24h
    settings: |
      max_file_store: 1GB
    {{- with .Values.nodeSelector }}
    nodeSelector: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations: {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
