{{- if .Values.ingress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4}}
  labels:
    businessid: {{ required "businessid must be provided" .Values.businessid | quote }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
    {{- range .Values.ingress.tls.hosts }}
        - "{{ .host }}"
    {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    -
      {{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host }}
      {{- end }}
      http:
        paths:
        - backend:
            service:
              name: {{ .Values.name }}-eventsource-svc
              port: 
                number: {{ .Values.eventsource.config.servicePort }}
          path: {{ .Values.ingress.path }}
          pathType: ImplementationSpecific
{{- end -}}
