apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wf-role-binding-{{ .Values.name }}-executor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wf-role-{{ .Values.name }}-executor
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-pod-service-account