{{- range $secret_name, $ref := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
data:
  {{- range $key, $value := $ref.data }}
    {{ $key | quote }} : {{ $value | quote }}
  {{- end }}
stringData:
  {{- range $key, $value := $ref.stringData }}
  {{ $key | quote }} : {{ $value | quote }}
  {{- end }}
{{- end }}