apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    businessid: {{ required "businessid must be provided" .Values.businessid | quote }}
spec: {{- include "workflow-library.argo_workflow_workflow.template" . | nindent 2 }}