{{- if and (required "kind must be provided" .Values.kind ) (eq .Values.kind "CronWorkflow") }}
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {{ required "name must be provided"  .Values.name }} 
  namespace: {{ .Release.Namespace }}
spec:
  schedule: '{{ required "schedule must be provided" .Values.schedule }}'
  {{- if and (.Values.job) (.Values.job.history) (.Values.job.history.success) }}
  successfulJobsHistoryLimit: {{ .Values.job.history.success }}
  {{- else }}
  successfulJobsHistoryLimit: 3
  {{- end }}
  {{- if and (.Values.job) (.Values.job.history) (.Values.job.history.failed) }}
  failedJobsHistoryLimit: {{ .Values.job.history.failed }}
  {{- else }}
  failedJobsHistoryLimit: 1
  {{- end }}
  {{- if and (.Values.job) (.Values.job.concurrency) }}
  concurrencyPolicy: {{ .Values.job.concurrency }}                    # Valid Value:  "Allow" | "Forbid" | "Replace"
  {{- else }}
  concurrencyPolicy:  "Allow"
  {{- end }}
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  workflowSpec:
    workflowMetadata:
      labels:
        name: {{ .Values.name }}
      {{- range $key, $value := .Values.annotations }}
      {{ $key | quote }} : {{ $value | quote }}
      {{- end }}  
    {{- if .Values.serviceaccount }}
    serviceAccountName: {{ .Values.serviceaccount.name | default (printf "%s-argo-workflows-admin-service-account" .Release.Namespace) }}
    {{- else if .Values.serviceAccount }}
    serviceAccountName: {{ .Release.Namespace  }}-argo-workflows-admin-service-account
    {{- end }}  
    {{- if and (.Values.job) (.Values.job.timeout) }}
    activeDeadlineSeconds	: {{.Values.job.timeouts }}
    {{- end }}         
    metrics:
      prometheus:
        - name: exec_duration_gauge                                   # Metric name (will be prepended with "argo_workflows_")
          labels:                                                     # Labels are optional. Avoid cardinality explosion.
            - key: name
              value: "{{ "{{" }}workflow.labels.name{{ "}}" }}"
            - key: kind
              value: "cron-workflow"
          help: "Duration gauge by name"                              # A help doc describing your metric. This is required.
          gauge:                                                      # The metric type. Available are "gauge", "histogram", and "counter".
            value: "{{ "{{" }}workflow.duration{{ "}}" }}"            # The value of your metric. It could be an Argo variable (see variables doc) or a literal value
        - name: cron_workflow_fail_count
          labels:
            - key: name
              value: "{{ "{{" }}workflow.labels.name{{ "}}" }}"
            - key: namespace
              value: "{{ "{{" }}workflow.namespace{{ "}}" }}"
            - key: kind
              value: "cron-workflow"
          help: "Count of execution by fail status"                  
          when: "{{ "{{" }}status{{ "}}" }} != Succeeded"             # Emit the metric conditionally. Works the same as normal "when"
          counter:
            value: "1"                                                # This increments the counter by 1
        - name: cron_workflow_success_count
          labels:
            - key: name
              value: "{{ "{{" }}workflow.labels.name{{ "}}" }}"
            - key: namespace
              value: "{{ "{{" }}workflow.namespace{{ "}}" }}"
            - key: kind
              value: "cron-workflow"
          help: "Count of execution by success status"                            
          when: "{{ "{{" }}status{{ "}}" }} == Succeeded"             # Emit the metric conditionally. Works the same as normal "when"
          counter:
            value: "1"                                                # This increments the counter by 1
    entrypoint: entry
    onExit: exit-handler
    templates:
      - name: entry
        steps:
          - - name: step1
              template: template
        {{- if and  (.Values.job) (.Values.job.retries)}}      
        retryStrategy:                                                # will cause a container to retry until completion if it is empty 
          limit: {{ .Values.job.retries }}
          {{- if .Values.job.retryPolicy }} 
          retryPolicy: {{ .Values.job.retryPolicy }}                  # Valid Value:  "Allow" | "Forbid" | "Replace" 
          {{- end }}  
        {{- end }}        
      - name: template
        metadata:
          namespace: {{ .Release.Namespace }}
          kind: "cron-workflow"    
        container:
          image: '{{ required "image.repository must be provided" .Values.image.repository }}:{{ required "image.tag must be provided" .Values.image.tag }}'
          {{- if .Values.command }}
          command:  {{- toYaml ( .Values.command) | nindent 11 }}
          {{- end }}
          {{- if .Values.command }}
          args: {{- toYaml ( .Values.args) | nindent 11 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml ( .Values.resources) | nindent 11 }}
          {{- else }}   # default settings on resources
          resources:  
            limits:
              memory: "4Gi"
            requests:
              cpu: "0.5"
              memory: "3Gi"
          {{- end }}
          env:
            - name: POD_NAME
              value: {{ .Values.name }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $name := .Values.envSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $name }}
                  key: {{ $key | quote }}
            {{- end }}          
          {{- if .Values.envFrom }}
          envFrom:
            {{- range .Values.envFrom.configMapRef }}
            - configMapRef:
                name: {{ . }}
            {{- end }}
            {{- range .Values.envFrom.secretRef }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          {{- end }}
      - name: exit-handler
        steps:
        - - name: Success
            template: success-handler
            when: "{{ "{{" }}workflow.status{{ "}}" }} == Succeeded" 
          - name: Failed
            template: failed-handler
            when: "{{ "{{" }}workflow.status{{ "}}" }} != Succeeded"
      - name: success-handler                                                 # template for the success case
        steps: 
        - - name: Notice-Health-Check-Succeed
            template: notice-health-check-succeed            
      - name: failed-handler                                                  # template for the failed case
        steps: 
        - - name: Notice-Health-Check-Failed
            template: notice-health-check-failed 
          {{- if  (.Values.newrelicEnable) }}          
          - name: Notice-NewRelic-Failed
            template: notice-newrelic-failed            
          {{- end }}    
      - name: notice-health-check-succeed                                    # For cronjob health check, as the schedule may different therefore each cronjob will have different uuid
        container:
          image: curlimages/curl
          command: [ "sh", "-c" ]
          args:
            - curl https://hc-ping.com/{{ required "healthCheck.successUUID must be provided" .Values.healthCheckSuccessUUID }}
      - name: notice-health-check-failed
        container:
          image: curlimages/curl
          command: [ "sh", "-c" ]
          args:
            - curl https://hc-ping.com/{{ required "healthCheck.failUUID must be provided" .Values.healthCheckFailUUID }}
      {{- if  (.Values.newrelicEnable) }}                                        
      - name: notice-newrelic-failed
        container:
          image: johnku001/newrelic-notice-error-agent
          env:
            - name: NEWRELIC_APP_NAME
              value: "Argo Workflow Cronjob (Staging)"        
            - name: FUNCTION_NAME
              value: ""        
            - name: NEWRELIC_LICENSE_KEY
              value: ""                                
            # - name: ENV
            #   valueFrom:
            #     fieldRef:
            #       fieldPath: metadata.namespace        
          args:
            - error={{ "{{" }}workflow.failures{{ "}}" }} 
            - workflow_name="{{ "{{" }}workflow.name{{ "}}" }}" 
            - workflow_status="{{ "{{" }}workflow.status{{ "}}" }}" 
            - workflow_duration="{{ "{{" }}workflow.duration{{ "}}" }}"
      {{- end }}                 
    {{- if .Values.keepPodAfterFinish }}                               # Can keep the pod after finish during development
    ttlStrategy:
      secondsAfterCompletion: 600    
    podGC:
      labelSelector:
        matchLabels:
          should-be-deleted: "true"
    {{- end }}
{{- end }}

{{- if and (required "kind must be provided" .Values.kind ) (eq .Values.kind "CronJob") }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.job.history.success | default 3 }}
  failedJobsHistoryLimit: {{ .Values.job.history.failed | default 1 }}
  concurrencyPolicy: {{ .Values.job.concurrency | default "Allow" }}
  {{- if .Values.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    metadata:
      annotations:
        cronjob_name: {{ .Values.name }}
    spec:
      backoffLimit: {{ .Values.job.retries }}
      activeDeadlineSeconds: {{ .Values.job.timeout }}
      template:
        metadata:
          annotations:
            cronjob_name: {{ .Values.name }}
            {{- range $key, $value := .Values.annotations }}
            {{ $key | quote }} : {{ $value | quote }}
            {{- end }}
        spec:
          {{- if .Values.serviceaccount }}
          serviceAccountName: {{ .Values.serviceaccount.name | default (printf "%s-pod-service-account" .Values.name) }}
          {{- else if .Values.serviceAccount }}
          serviceAccountName: {{ .Values.name }}-pod-service-account
          {{- end }}
          restartPolicy: Never
          containers:
            -
              name: app
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              {{- if .Values.command }}
              command: {{- toYaml .Values.command | nindent 16 }}
              {{- end }}
              {{- if hasKey .Values "resources" }}
              resources: {{ toYaml .Values.resources | nindent 16 }}
              {{- end }}
              env:
                - name: POD_NAME
                  value: {{ .Values.name }}
                {{- range $key, $value := .Values.env }}
                - name: {{ $key }}
                  value: {{ $value | quote }}
                {{- end }}
                {{- range $key, $name := .Values.envSecrets }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $name }}
                      key: {{ $key | quote }}
                {{- end }}
              {{- if .Values.envFrom }}
              envFrom:
                {{- range .Values.envFrom.configMapRef }}
                - configMapRef:
                    name: {{ . }}
                {{- end }}
                {{- range .Values.envFrom.secretRef }}
                - secretRef:
                    name: {{ . }}
                {{- end }}
              {{- end }}
{{- end }}
    