{{- if .Values.hpa }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  scaleTargetRef:
    {{- if .Values.rollout }}
    kind: Rollout
    apiVersion: argoproj.io/v1alpha1
    {{- else }}
    kind: Deployment
    apiVersion: apps/v1
    {{- end }}
    name: {{ .Values.name }}
  metrics:
  {{- range .Values.hpa.Resource }}
  - type: Resource
    resource:
      name: {{ .name }}
      target:
        {{- if .percent}}
        type: Utilization
        averageUtilization: {{ .percent }}
        {{- else if .value}}
        type: AverageValue
        averageValue: {{ .value }}
        {{- end }}
  {{- end }}
{{- end }}