{{- if .Values.ingress }}
{{ include "simple.validateRequired" . }}
{{- if hasKey .Values "EnableMutilpleIngress" }}
{{ template "ingress.ingress_multiple" . }}
{{- else }}
{{ template "ingress.ingress_single" . }}
{{- end }}
{{- end }}