{{- if .Values.pdb }}
{{- if eq .Values.pdb.enable true }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.pdb.maxUnavailable (not .Values.pdb.minAvailable) }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 50% }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
{{- end }}
{{- end }}
