{{ include "simple.validatePVC" . }}
{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    businessid: {{ $.Values.businessid | quote }}
    app: {{ .Values.name }}
spec:
  accessModes:
  {{- if not (empty .Values.persistence.accessModes) }}
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.selector }}
  dataSource:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}