{{- if .Values.serviceaccount }}
{{- if .Values.serviceaccount.skipCreation }}
{{- /*
Skip create service account
*/}}
{{- else}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {{ toYaml .Values.serviceaccount.annotations | nindent 4}}
  name: {{ .Values.serviceaccount.name | default (printf "%s-pod-service-account" .Values.name) }}
{{- end}}
{{- end}}
